### ISSUE TITLE
partition table error

### ISSUE THREAD

**Issue by SamirDasarwad** [chegewara/esp32-ota-with-ble-setup#3]
@chegewara  i try to compile your code as it is but i am getting errors about partition table 

**/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: In function 'load_partition_table':
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:160:34: error: 'ESP_PARTITION_TABLE_ADDR' undeclared (first use in this function)
     partitions = bootloader_mmap(ESP_PARTITION_TABLE_ADDR, ESP_PARTITION_TABLE_DATA_LEN);**
                                  ^
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:160:34: note: each undeclared identifier is reported only once for each function it appears in
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:167:5: warning: 'esp_partition_table_basic_verify' is deprecated [-Wdeprecated-declarations]
     err = esp_partition_table_basic_verify(partitions, true, &num_partitions);
     ^
In file included from /home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_image_format.h:18:0,
                 from /home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:44:
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_flash_partitions.h:42:53: note: declared here
 inline static __attribute__((deprecated)) esp_err_t esp_partition_table_basic_verify(const esp_partition_info_t *partition_table, bool log_errors, int *num_partitions)
                                                     ^
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: In function 'try_load_partition':
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:402:5: warning: 'esp_image_load' is deprecated [-Wdeprecated-declarations]
     if (esp_image_load(ESP_IMAGE_LOAD, partition, data) == ESP_OK) {
     ^
In file included from /home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:44:0:
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_image_format.h:141:11: note: declared here
 esp_err_t esp_image_load(esp_image_load_mode_t mode, const esp_partition_pos_t *part, esp_image_metadata_t *data) __attribute__((deprecated));
           ^
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: At top level:
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:297:16: warning: 'ForceFactoryBoot' defined but not used [-Wunused-function]
 static uint8_t ForceFactoryBoot(void)
                ^
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/make/component_wrapper.mk:285: recipe for target 'bootloader_start.o' failed
make[2]: *** [bootloader_start.o] Error 1
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/make/project.mk:530: recipe for target 'component-main-build' failed
make[1]: *** [component-main-build] Error 2
/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/components/bootloader/Makefile.projbuild:40: recipe for target '/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin' failed
make: *** [/home/firewires/Desktop/esp/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin] Error 2

**Comment by chegewara** [comment]
What version of esp-idf are you using?
This error seems to be from esp-idf not my code.

**Comment by SamirDasarwad** [comment]
make version                                                                                                                                                                [23:43:07]
Toolchain path: /home/firewires/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
make: *** No rule to make target 'version'.  Stop.

**Comment by chegewara** [comment]
I am asking about esp-idf, not toolchain.

**Comment by SamirDasarwad** [comment]
make --version                                                                                                                                                              [23:44:16]
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by SamirDasarwad** [comment]
sry give me minute

**Comment by SamirDasarwad** [comment]
v3.2.2 i am new to iot so learning by following

**Comment by SamirDasarwad** [comment]
when i use make it asks for some options
 **make                                                                                                                                                                        [23:50:38]
GENCONFIG
*
* Restart config...
*
*
* Bootloader config
*
Bootloader log verbosity
  1. No output (LOG_BOOTLOADER_LEVEL_NONE)
  2. Error (LOG_BOOTLOADER_LEVEL_ERROR)
  3. Warning (LOG_BOOTLOADER_LEVEL_WARN)
  4. Info (LOG_BOOTLOADER_LEVEL_INFO)
  5. Debug (LOG_BOOTLOADER_LEVEL_DEBUG)
> 6. Verbose (LOG_BOOTLOADER_LEVEL_VERBOSE)
choice[1-6?]: 6
SPI Flash WP Pin when customising pins via efuse (read help) (BOOTLOADER_SPI_WP_PIN) [7] (NEW)**

**Comment by chegewara** [comment]
With this version it should works.

> when i use make it asks for some options

try `make defconfig`

**Comment by SamirDasarwad** [comment]
**$] make defconfig                                                                                             [23:53:18]
Toolchain path: /home/firewires/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
DEFCONFIG
#
# configuration written to /home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/sdkconfig
#
┌─[firewires@firewires] - [~/Desktop/esp/testota/esp32-ota-with-ble-setup-master] - [1640]
└─[$] make flash monitor                                                                                         [23:53:26]
Toolchain path: /home/firewires/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
GENCONFIG
CC build/bootloader/bootloader_support/src/efuse.o
CC build/bootloader/bootloader_support/src/bootloader_flash.o
CC build/bootloader/bootloader_support/src/flash_qio_mode.o
CC build/bootloader/bootloader_support/src/secure_boot_signatures.o
CC build/bootloader/bootloader_support/src/bootloader_init.o
CC build/bootloader/bootloader_support/src/bootloader_utility.o
CC build/bootloader/bootloader_support/src/bootloader_common.o
CC build/bootloader/bootloader_support/src/secure_boot.o
CC build/bootloader/bootloader_support/src/bootloader_clock.o
CC build/bootloader/bootloader_support/src/flash_partitions.o
CC build/bootloader/bootloader_support/src/esp_image_format.o
CC build/bootloader/bootloader_support/src/bootloader_sha.o
CC build/bootloader/bootloader_support/src/flash_encrypt.o
CC build/bootloader/bootloader_support/src/bootloader_random.o
AR build/bootloader/bootloader_support/libbootloader_support.a
CC build/bootloader/log/log.o
AR build/bootloader/log/liblog.a
CC build/bootloader/spi_flash/spi_flash_rom_patch.o
AR build/bootloader/spi_flash/libspi_flash.a
CC build/bootloader/soc/esp32/cpu_util.o
CC build/bootloader/soc/esp32/rtc_time.o
CC build/bootloader/soc/esp32/rtc_init.o
CC build/bootloader/soc/esp32/rtc_clk_init.o
CC build/bootloader/soc/esp32/rtc_sleep.o
CC build/bootloader/soc/esp32/rtc_clk.o
CC build/bootloader/soc/src//memory_layout_utils.o
AR build/bootloader/soc/libsoc.a
CC build/bootloader/main/bootloader_start.o
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: In function 'load_partition_table':
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:160:34: error: 'ESP_PARTITION_TABLE_ADDR' undeclared (first use in this function)
     partitions = bootloader_mmap(ESP_PARTITION_TABLE_ADDR, ESP_PARTITION_TABLE_DATA_LEN);
                                  ^
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:160:34: note: each undeclared identifier is reported only once for each function it appears in
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:167:5: warning: 'esp_partition_table_basic_verify' is deprecated [-Wdeprecated-declarations]
     err = esp_partition_table_basic_verify(partitions, true, &num_partitions);
     ^
In file included from /home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_image_format.h:18:0,
                 from /home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:44:
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_flash_partitions.h:42:53: note: declared here
 inline static __attribute__((deprecated)) esp_err_t esp_partition_table_basic_verify(const esp_partition_info_t *partition_
                                                     ^
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: In function 'try_load_partition':
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:402:5: warning: 'esp_image_load' is deprecated [-Wdeprecated-declarations]
     if (esp_image_load(ESP_IMAGE_LOAD, partition, data) == ESP_OK) {
     ^
In file included from /home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:44:0:
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/components/bootloader_support/include/esp_image_format.h:141:11: note: declared here
 esp_err_t esp_image_load(esp_image_load_mode_t mode, const esp_partition_pos_t *part, esp_image_metadata_t *data) __attribu
           ^
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c: At top level:
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/subproject/main/bootloader_start.c:297:16: warning: 'ForceFactoryBoot' defined but not used [-Wunused-function]
 static uint8_t ForceFactoryBoot(void)
                ^
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/make/component_wrapper.mk:285: recipe for target 'bootloader_start.o' failed
make[2]: *** [bootloader_start.o] Error 1
/home/firewires/Desktop/esp/esp-iot-solution/submodule/esp-idf/make/project.mk:530: recipe for target 'component-main-build' failed
make[1]: *** [component-main-build] Error 2
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/Makefile.projbuild:40: recipe for target '/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin' failed
make: *** [/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin] Error 2**

**Comment by SamirDasarwad** [comment]
when i am using ESP-IDF v4.1-dev-437-gd2ad0f077-dirty
it gives different error like


**### **### make                                                                                                                                                                        [23:57:09]
Toolchain path: /home/firewires/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-80-g6c4433a
Expected to see version: esp32-2019r1
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 5.2.0
Expected to see version(s): 8.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
Python requirements from /home/firewires/Desktop/esp/esp-idf/requirements.txt are satisfied.
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-80-g6c4433a
Expected to see version: esp32-2019r1
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 5.2.0
Expected to see version(s): 8.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Missing submodule components/esp32/lib...
Attempting 'git submodule update --init components/esp32/lib' in esp-idf root directory...
error: pathspec 'components/esp32/lib' did not match any file(s) known to git.
/home/firewires/Desktop/esp/esp-idf/make/project.mk:663: recipe for target '/home/firewires/Desktop/esp/esp-idf/components/esp32/lib/.git' failed
make[1]: *** [/home/firewires/Desktop/esp/esp-idf/components/esp32/lib/.git] Error 1
/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/components/bootloader/Makefile.projbuild:40: recipe for target '/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin' failed
make: *** [/home/firewires/Desktop/esp/testota/esp32-ota-with-ble-setup-master/build/bootloader/bootloader.bin] Error 2****

**Comment by chegewara** [comment]
Ok, code is very old, so probably its meant to be used with esp-idf v2.x.

**Comment by SamirDasarwad** [comment]
ok thanks i will try with v2.x but what if i want to use code with other version 
and i want to do BLE and OTA in same factory partition for provisioning and downloading new bin file ?
any suggestion

**Comment by chegewara** [comment]
You can use OTA and BLE at the same time.
This code was make some setup over BLE, like wifi credentials and binary file URL to perform OTA update. It was like demo, when i started to learn esp32 programming.

**Comment by SamirDasarwad** [comment]
any resources if available for doing these kind of demo i currently working on esp32 and AWS i have check amazon demo but seems it not much help do you have suggestion to follow up any website or book thanks for help :+1: )

**Comment by chegewara** [comment]
https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html
https://docs.aws.amazon.com/freertos/latest/userguide/building-cmake-prereqs.html
https://docs.aws.amazon.com/freertos/latest/userguide/freertos-getting-started.html

**Comment by SamirDasarwad** [comment]
thanks for the help so i am closing the issue
